/**
 * Neovim Artifact Generator
 *
 * Generates the Neovim-side highlighting artifacts for `.lolo` and `.orb`:
 *
 * - `queries/lolo/highlights.scm` — tree-sitter query against the same
 *   `tree-sitter-lolo` grammar Zed uses, written with Neovim's standard
 *   capture names (`:h treesitter-highlight-groups`).
 * - `queries/orb/highlights.scm` — tree-sitter query for `.orb`, whose parser
 *   is the stock JSON grammar registered under the language name `orb` (see
 *   `editors/nvim/lua/almadar/treesitter.lua`); the s-expression layer is
 *   `#any-of?` predicates over `(string_content)`.
 * - `syntax/lolo.vim` / `syntax/orb.vim` — the regex fallback for Neovim
 *   builds without the tree-sitter parsers, ported from the TextMate grammar
 *   in `lolo-grammar.ts` / `sexpr-grammar.ts` rule-for-rule.
 *
 * Every token list is sourced from @almadar/syntax's `tokens.json` — the same
 * registry `lolo-grammar.ts` (VSCode + Zed) reads — so nothing here can drift
 * from the operator/pattern/behavior SSOT.
 *
 * Literal keywords are additionally intersected with the anonymous tokens the
 * real grammar declares (`tree-sitter-lolo/src/node-types.json`). A tree-sitter
 * query naming a token the parser has no node for fails to compile *as a
 * whole*, so a registry keyword the grammar has not caught up to (today:
 * `extends`) must be dropped from the query rather than silently breaking
 * every other rule in the file.
 *
 * @packageDocumentation
 */

import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLoloTokens } from './lolo-grammar.js';

// ============================================================================
// Grammar introspection
// ============================================================================

/** Path to the tree-sitter-lolo grammar sources, relative to this package. */
const GRAMMAR_DIR = join(
    dirname(fileURLToPath(import.meta.url)),
    '..',
    'editors',
    'zed',
    'tree-sitter-lolo',
    'src',
);

interface NodeTypeEntry {
    type: string;
    named: boolean;
}

export interface GrammarNodes {
    /** Named node types, e.g. `sexpr_op`, `entity_field`. */
    named: ReadonlySet<string>;
    /** Anonymous literal tokens, e.g. `"orbital"`, `"->"`, `"{"`. */
    anonymous: ReadonlySet<string>;
}

let cachedNodes: GrammarNodes | undefined;

/** Read the node types the generated `tree-sitter-lolo` parser actually declares. */
export function loadGrammarNodes(): GrammarNodes {
    if (cachedNodes) return cachedNodes;
    const raw = JSON.parse(
        readFileSync(join(GRAMMAR_DIR, 'node-types.json'), 'utf-8'),
    ) as NodeTypeEntry[];
    const named = new Set<string>();
    const anonymous = new Set<string>();
    for (const entry of raw) {
        (entry.named ? named : anonymous).add(entry.type);
    }
    cachedNodes = { named, anonymous };
    return cachedNodes;
}

// ============================================================================
// Shared helpers
// ============================================================================

const GENERATED_BANNER =
    '@almadar/extensions — regenerate with `pnpm run generate-grammar`. Do not edit.';

function scmHeader(what: string): string {
    return `; ${what}\n; GENERATED by ${GENERATED_BANNER}\n`;
}

/** Render a list as `#any-of?` arguments, one per line, sorted for stable diffs. */
function anyOfArgs(names: readonly string[], indent = '    '): string {
    return [...new Set(names)]
        .sort()
        .map((n) => `"${n.replace(/(["\\])/g, '\\$1')}"`)
        .join(`\n${indent}`);
}

/** Render a list as a tree-sitter alternation node list, wrapped at ~76 columns. */
function literalList(names: readonly string[], indent = '  '): string {
    return [...new Set(names)].sort().map((n) => `${indent}"${n}"`).join('\n');
}

function escapeRegex(str: string): string {
    return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Wrap a name in the literal double quotes a `.lolo` `string` token carries. */
function quoted(name: string): string {
    return `"${name}"`;
}

/**
 * Escape a literal for a Vim regex in *magic* mode — the default for `:syntax`.
 *
 * Only `\ . * [ ] ^ $ ~` are special there; `+ ? ( ) { } |` are literal and
 * become special only when backslash-escaped, so escaping them the JS way
 * (`escapeRegex`) would turn the operator name `+` into the quantifier `\+`.
 */
function vimEscape(str: string): string {
    return str.replace(/[\\.*[\]^$~]/g, '\\$&');
}

/** Longest-first alternation — a shorter operator must not shadow a longer one. */
function vimAlternation(words: readonly string[]): string {
    return [...new Set(words)]
        .sort((a, b) => b.length - a.length || a.localeCompare(b))
        .map(vimEscape)
        .join('\\|');
}

/** All namespaced runtime operators (`math/add`, `array/map`, …) across namespaces. */
function namespacedOperators(byNamespace: Record<string, string[]>): string[] {
    return Object.values(byNamespace)
        .flat()
        .filter((op) => op.includes('/'));
}

/** Control-flow + logic s-expr operators (`if`, `and`, `let`, `do`, `fn`, …). */
function controlOperators(byNamespace: Record<string, string[]>): string[] {
    return [...(byNamespace.control ?? []), ...(byNamespace.logic ?? [])];
}

/**
 * Bare arithmetic/comparison operators (`+`, `-`, `=`, `<=`, …).
 *
 * The registry's `arithmetic` and `comparison` buckets are mixed: they hold
 * both the bare symbolic operators and namespaced calls (`math/randomInt`,
 * `validate/required`). Only the bare ones belong to the operator colour —
 * the namespaced ones are picked up by `namespacedOperators`.
 */
function bareOperators(byNamespace: Record<string, string[]>): string[] {
    return [...(byNamespace.arithmetic ?? []), ...(byNamespace.comparison ?? [])]
        .filter((op) => !op.includes('/'));
}

// ============================================================================
// queries/lolo/highlights.scm
// ============================================================================

/**
 * Generate the Neovim tree-sitter highlights query for `.lolo`.
 *
 * Capture names are Neovim's standard groups, not Zed's. Precedence is
 * tree-sitter's: for the same node, a *later* pattern wins — so each generic
 * rule is stated first and the registry-driven `#any-of?` refinements follow.
 */
export function generateLoloNvimHighlights(): string {
    const tokens = loadLoloTokens();
    const { anonymous } = loadGrammarNodes();

    // Only literals the parser really has — see the module doc.
    const declarationKeywords = tokens.loloKeywords.filter((k) => anonymous.has(k));
    // Grammar-only keywords the token registry does not carry as `loloKeywords`.
    const extraKeywords = ['as', 'when', 'every', 'events', 'fields', 'emitsScope']
        .filter((k) => anonymous.has(k));
    const typeConstructors = ['Map', 'Entity', 'Event', 'Orbital', 'Page', 'Trait']
        .filter((k) => anonymous.has(k));

    const control = controlOperators(tokens.operatorsByNamespace);
    const namespaced = namespacedOperators(tokens.operatorsByNamespace);

    return `${scmHeader('.lolo — Neovim tree-sitter highlights')}
; ── Comments ────────────────────────────────────────────────────────────────
(comment) @comment @spell

; ── Declaration keywords ────────────────────────────────────────────────────
[
${literalList([...declarationKeywords, ...extraKeywords])}
] @keyword

${anonymous.has('@rebindable') ? '"@rebindable" @attribute\n' : ''}
; ── Built-in type constructors ──────────────────────────────────────────────
[
${literalList(typeConstructors)}
] @type.builtin

; ── Literals ────────────────────────────────────────────────────────────────
(string) @string
(number) @number
(boolean) @boolean
(null) @constant.builtin
(version_tag) @string.special
(duration) @number

; ── Bindings: @entity.field, @config.x, ?payload.field ──────────────────────
(sigil) @variable.builtin
(payload_sigil) @variable.builtin

; ── Events ──────────────────────────────────────────────────────────────────
(event_name) @constant
(event_arrow) @operator

; ── Declaration names ───────────────────────────────────────────────────────
(orbital name: (identifier) @type)
(entity name: (identifier) @type)
(trait name: (identifier) @type)
(trait entity: (identifier) @type)
(page name: (identifier) @type)
(page trait: (identifier) @type)
(page path: (string) @string.special.path)
(type_alias name: (identifier) @type)
(type_alias param: (identifier) @type.parameter)
(use_decl path: (string) @string.special.path)
(use_decl alias: (identifier) @type)
(dotted_reference (identifier) @type)
(dotted_reference (event_name) @constant)

; ── Members ─────────────────────────────────────────────────────────────────
(entity_field name: (identifier) @variable.member)
(config_field name: (identifier) @variable.member)
(type_object name: (identifier) @variable.member)
(object_literal key: (identifier) @variable.member)
(object_literal key: (string) @variable.member)
(state_block name: (identifier) @label)
(tick_decl name: (identifier) @function)
(emits_scope scope: (identifier) @keyword.modifier)
(emit_decl scope: (identifier) @keyword.modifier)

; ── Types ───────────────────────────────────────────────────────────────────
(type_atom (identifier) @type)
((type_atom (identifier) @type.builtin)
  (#any-of? @type.builtin
    ${anyOfArgs(tokens.loloPrimitiveTypes)}))

; ── Bracket tags: [runtime], [interaction], [shared] ────────────────────────
(bracket_tag key: (identifier) @constant.builtin)
(bracket_tag value: (identifier) @constant)
((bracket_tag key: (identifier) @keyword.modifier)
  (#any-of? @keyword.modifier
    ${anyOfArgs(tokens.loloPersistenceAndScope)}))
((bracket_tag key: (identifier) @attribute)
  (#any-of? @attribute
    ${anyOfArgs(tokens.loloTraitCategories)}))

; ── Annotations: @description, @synonyms, @label, @tier, … ──────────────────
(annotation_tag) @attribute

; ── JSX ─────────────────────────────────────────────────────────────────────
(jsx_tag_name) @tag
(jsx_attribute name: (identifier) @tag.attribute)

; ── S-expressions ───────────────────────────────────────────────────────────
; The call head is the FIRST NAMED CHILD of \`sexpr\`, not a \`sexpr_op\`:
; \`sexpr_op\` only materializes for symbol heads (\`(+ 1 2)\`, \`(= a b)\`)
; because of the declared \`[sexpr_op, _sexpr_arg]\` GLR conflict — for the
; overwhelmingly common identifier head (\`(set …)\`, \`(math/add …)\`) the
; \`_sexpr_arg\` parse wins and the head is a bare \`identifier\`. Anchoring on
; the first named child covers both shapes.
; Generic call head first; the registry-driven refinements below override it.
(sexpr . (identifier) @function)
(sexpr_op (operator_symbol) @operator)
(sexpr_op "=" @operator)

; Namespaced runtime operators: math/add, array/map, str/join, …
((sexpr . (identifier) @function.builtin)
  (#any-of? @function.builtin
    ${anyOfArgs(namespaced)}))

; Control-flow / logic operators: if, and, or, not, let, do, fn, …
((sexpr . (identifier) @keyword.conditional)
  (#any-of? @keyword.conditional
    ${anyOfArgs(control)}))

; Effect operators: set, emit, persist, fetch, render-ui, navigate, …
((sexpr . (identifier) @keyword.function)
  (#any-of? @keyword.function
    ${anyOfArgs(tokens.effectTypes)}))

; ── Registry names inside string literals ───────────────────────────────────
; \`string\` is an atomic token in this grammar (quotes included, no
; \`string_content\` child), so the predicates match the quoted form.
((string) @type.builtin
  (#any-of? @type.builtin
    ${anyOfArgs(tokens.patternNames.map(quoted))}))

((string) @function.builtin
  (#any-of? @function.builtin
    ${anyOfArgs(tokens.behaviorNames.map(quoted))}))

; ── Punctuation ─────────────────────────────────────────────────────────────
[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
] @punctuation.bracket

[
  ","
  ":"
  "::"
  "."
] @punctuation.delimiter

(arrow) @operator

[
  "="
  "!"
  "*"
  "+"
  "?"
  "|"
  "&"
] @operator
`;
}

// ============================================================================
// queries/orb/highlights.scm
// ============================================================================

/**
 * Generate the Neovim tree-sitter highlights query for `.orb`.
 *
 * `.orb` is JSON, so the parser is the stock `json` grammar loaded under the
 * language name `orb`; the s-expression layer rides on `(string_content)`
 * predicates. Unlike the hand-written Zed equivalent this is generated from
 * the operator registry, so a new operator is coloured on the next build.
 */
export function generateOrbNvimHighlights(): string {
    const tokens = loadLoloTokens();
    const require = createRequire(import.meta.url);
    const rawTokens = JSON.parse(
        readFileSync(require.resolve('@almadar/syntax/tokens.json'), 'utf-8'),
    ) as { uiSlots?: string[]; structuralKeys?: string[] };

    const control = controlOperators(tokens.operatorsByNamespace);
    const namespaced = namespacedOperators(tokens.operatorsByNamespace);
    const bare = bareOperators(tokens.operatorsByNamespace);

    return `${scmHeader('.orb — Neovim tree-sitter highlights (JSON grammar under language `orb`)')}
; ── JSON base ───────────────────────────────────────────────────────────────
(pair key: (string) @variable.member)
(string) @string
(number) @number
[(true) (false)] @boolean
(null) @constant.builtin
["{" "}" "[" "]"] @punctuation.bracket
["," ":"] @punctuation.delimiter
(comment) @comment @spell

; ── S-expression layer (arrays of strings inside the IR) ────────────────────
; Namespaced runtime operators: math/add, array/map, str/join, …
((string_content) @function.builtin
  (#any-of? @function.builtin
    ${anyOfArgs(namespaced)}))

; Arithmetic / comparison operators
((string_content) @operator
  (#any-of? @operator
    ${anyOfArgs(bare)}))

; Control-flow / logic operators
((string_content) @keyword.conditional
  (#any-of? @keyword.conditional
    ${anyOfArgs(control)}))

; Effect operators
((string_content) @keyword.function
  (#any-of? @keyword.function
    ${anyOfArgs(tokens.effectTypes)}))

; UI slots: main, sidebar, modal, hud-top, …
((string_content) @tag
  (#any-of? @tag
    ${anyOfArgs(rawTokens.uiSlots ?? [])}))

; UI pattern names
((string_content) @markup.link
  (#any-of? @markup.link
    ${anyOfArgs(tokens.patternNames)}))

; Behavior names: std-browse, std-calendar, …
((string_content) @function
  (#any-of? @function
    ${anyOfArgs(tokens.behaviorNames)}))

; Bindings: @entity.*, @payload.*, @context.*, @config.*, @user.*
; \`#match?\` compiles with Vim's regex engine in VERY MAGIC mode — Neovim
; prepends \`\\v\` (\`runtime/lua/vim/treesitter/query.lua\`, check_magic).
; So \`(\`/\`|\`/\`{\` are PCRE-like, but \`@\` is the operator prefix
; (\`@=\`, \`@<=\`) and a literal \`@\` must be escaped. Tree-sitter also
; strips one backslash off every escape in a query string, hence \`\\\\@\`
; here to reach the engine as \`\\@\`.
((string_content) @variable.builtin
  (#match? @variable.builtin "^\\\\@(entity|payload|context|config|user|item|index)(\\\\.|$)"))

; Event keys: UPPER_SNAKE_CASE
((string_content) @constant
  (#match? @constant "^[A-Z][A-Z0-9_]{2,}$"))

; ── Structural keys of the .orb IR ──────────────────────────────────────────
; Last, so an object KEY always outranks the value-shaped rules above — a key
; that happens to spell a pattern or operator name stays a key.
((pair key: (string (string_content) @keyword))
  (#any-of? @keyword
    ${anyOfArgs(rawTokens.structuralKeys ?? [])}))
`;
}

// ============================================================================
// syntax/lolo.vim — regex fallback
// ============================================================================

/**
 * Generate the Vim regex syntax file for `.lolo` — the fallback when the
 * tree-sitter parser is unavailable (and the only highlighter for the handful
 * of files the grammar cannot yet parse; see the plugin README).
 *
 * Ported rule-for-rule from `generateLoloTmLanguage()`. Vim resolves same-start
 * collisions by *definition order* (last wins) and always lets `:syn keyword`
 * beat a `:syn match`, so rules are emitted in reverse TextMate precedence.
 */
export function generateLoloVimSyntax(): string {
    const tokens = loadLoloTokens();
    const namespaced = namespacedOperators(tokens.operatorsByNamespace);
    const control = controlOperators(tokens.operatorsByNamespace);

    // `-` and `/` are word characters in lolo (render-ui, math/add, game-core),
    // so `:syn keyword` needs them in 'iskeyword' or it will never match them.
    return `" .lolo syntax — the regex fallback for Neovim without tree-sitter.
" GENERATED by ${GENERATED_BANNER}

if exists("b:current_syntax")
  finish
endif

syn iskeyword @,48-57,_,-,/,192-255
syn case match

" ── Lowest precedence first: Vim gives a later definition priority ──────────
syn match loloPunctuation "-->\\|--\\|[{}()\\[\\]:,|&]"
syn match loloModifier "[!*+]\\(\\s\\|$\\|,\\|)\\|\\]\\|}\\)\\@="
syn match loloNumber "-\\=\\<\\d\\+\\%(\\.\\d*\\)\\=\\>"
syn match loloArrow "->\\|→\\|::\\|="
syn match loloConstructor "\\<\\u\\w*\\>"
syn match loloUnknownOperator "\\<\\l[a-z0-9_]*/[a-z][a-z0-9/_-]*\\>"
syn match loloEvent "\\<\\u[A-Z0-9_]\\+\\>"
syn match loloReference "\\<\\u\\w*\\%(\\.\\a\\w*\\)\\+\\>"
syn match loloBinding "[@?]\\a[a-zA-Z0-9_.]*"

" ── Keywords always outrank matches at the same position ────────────────────
syn keyword loloKeyword ${[...tokens.loloKeywords].sort().join(' ')} as when every
syn keyword loloType ${[...tokens.loloPrimitiveTypes].sort().join(' ')}
syn keyword loloTypeConstructor Map Entity Event Orbital Page Trait
syn keyword loloPersistence ${[...tokens.loloPersistenceAndScope].sort().join(' ')}
syn keyword loloCategory ${[...tokens.loloTraitCategories].sort().join(' ')}
syn keyword loloBoolean true false
syn keyword loloNull null
syn keyword loloEffect ${[...tokens.effectTypes].sort().join(' ')}
syn keyword loloStdOperator ${[...new Set(namespaced)].sort().join(' ')}
syn keyword loloControl ${[...new Set(control)].sort().join(' ')}

" ── Strings and comments consume everything inside them ─────────────────────
syn match loloEscape +\\\\[ntr"\\\\/]+ contained
syn region loloString start=+"+ skip=+\\\\.+ end=+"+ contains=loloEscape,@Spell
syn region loloBlockComment start="#=" end="=#" contains=@Spell
syn match loloComment ";;.*$" contains=@Spell
syn match loloComment "#\\%(=\\)\\@!.*$" contains=@Spell

hi def link loloComment        Comment
hi def link loloBlockComment   Comment
hi def link loloString         String
hi def link loloEscape         SpecialChar
hi def link loloBinding        Identifier
hi def link loloReference      Type
hi def link loloEvent          Constant
hi def link loloKeyword        Keyword
hi def link loloEffect         Statement
hi def link loloControl        Conditional
hi def link loloStdOperator    Function
hi def link loloUnknownOperator Error
hi def link loloType           Type
hi def link loloTypeConstructor Type
hi def link loloPersistence    StorageClass
hi def link loloCategory       PreProc
hi def link loloConstructor    Structure
hi def link loloArrow          Operator
hi def link loloNumber         Number
hi def link loloBoolean        Boolean
hi def link loloNull           Constant
hi def link loloModifier       Operator
hi def link loloPunctuation    Delimiter

let b:current_syntax = "lolo"
`;
}

// ============================================================================
// syntax/orb.vim — regex fallback
// ============================================================================

/**
 * Generate the Vim regex syntax file for `.orb`: stock JSON syntax plus the
 * s-expression injection, ported from `generateSExprGrammar()`'s lookaround
 * patterns (`(?<=")op(?=")` → `"\@<=op"\@=`).
 */
export function generateOrbVimSyntax(): string {
    const tokens = loadLoloTokens();
    const require = createRequire(import.meta.url);
    const rawTokens = JSON.parse(
        readFileSync(require.resolve('@almadar/syntax/tokens.json'), 'utf-8'),
    ) as { uiSlots?: string[] };

    const namespaced = namespacedOperators(tokens.operatorsByNamespace);
    const control = controlOperators(tokens.operatorsByNamespace);
    const arith = bareOperators(tokens.operatorsByNamespace);

    // Matched inside jsonString, anchored on the surrounding quotes so an
    // operator name never lights up inside prose. `#` delimits the pattern:
    // the usual `+` and `/` both occur *as operator names* in these lists.
    const inString = (name: string, alternation: string) =>
        `syn match ${name} #"\\@<=\\%(${alternation}\\)"\\@=# contained containedin=jsonString`;

    return `" .orb syntax — JSON plus the S-expression layer; the regex fallback for
" Neovim without tree-sitter.
" GENERATED by ${GENERATED_BANNER}

if exists("b:current_syntax")
  finish
endif

runtime! syntax/json.vim
unlet! b:current_syntax

${inString('orbStdOperator', vimAlternation(namespaced))}
${inString('orbOperator', vimAlternation(arith))}
${inString('orbControl', vimAlternation(control))}
${inString('orbEffect', vimAlternation(tokens.effectTypes))}
${inString('orbSlot', vimAlternation(rawTokens.uiSlots ?? []))}
${inString('orbBehavior', vimAlternation(tokens.behaviorNames))}
syn match orbBinding #"\\@<=@\\%(entity\\|payload\\|context\\|config\\|user\\|item\\|index\\)\\%(\\.[a-zA-Z_][a-zA-Z0-9_.]*\\)\\="\\@=# contained containedin=jsonString
syn match orbEvent #"\\@<=\\u[A-Z0-9_]\\{2,}"\\@=# contained containedin=jsonString

hi def link orbEffect       Statement
hi def link orbControl      Conditional
hi def link orbOperator     Operator
hi def link orbStdOperator  Function
hi def link orbBehavior     Function
hi def link orbBinding      Identifier
hi def link orbEvent        Constant
hi def link orbSlot         Tag

let b:current_syntax = "orb"
`;
}
